project:
  type: website

website:
  title: "ASA BIOP SWE WG"
  favicon: "sticker/sticker-600.png"
  navbar:
    logo: "sticker/sticker-300.png"
    left:
      - href: index.qmd
        text: "Home"
      - text: "About Us"
        menu:
          - href: goals.qmd
          - href: people.qmd
          - href: join_us.qmd
          - href: contact_us.qmd
      - href: news.qmd
        text: "News"
      - href: blog.qmd
        text: "Blog"
      - text: "Task Forces"
        menu:
          - href: mmrm_R_package.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

